"""Product-level diagnostic visualization helpers."""

from __future__ import annotations

import csv
import textwrap
from pathlib import Path

from constants import (
    DEFAULT_BACKGROUND_STYLE,
    IMAGE_EXTENSIONS,
    MASKS_DIR,
    MAX_VISUALIZATION_IMAGES,
    OUTPUTS_DIR,
    RAW_IMAGES_DIR,
    TEST_IMAGE_NAME,
)


def _parse_float(value: str | None) -> float | None:
    if value in (None, "", "None"):
        return None
    try:
        return float(value)
    except ValueError:
        return None


def _format_angle(value: str | float | None) -> str:
    angle = _parse_float(str(value)) if value is not None else None
    return "N/A" if angle is None else f"{angle:.1f} deg"


def _format_metric(value: str | None) -> str:
    metric = _parse_float(value)
    return "N/A" if metric is None else f"{metric:.3f}"


def _format_shadow_vector(row: dict[str, str], key: str) -> str:
    angle = _parse_float(row.get(f"shadow_angle_{key}"))
    dx = _parse_float(row.get(f"shadow_dx_{key}"))
    dy = _parse_float(row.get(f"shadow_dy_{key}"))
    if angle is None or dx is None or dy is None:
        return "N/A"
    return f"{angle:.1f} deg, dx={dx:.0f}px, dy={dy:.0f}px"


def _angle_to_direction(theta: float | None) -> str | None:
    if theta is None:
        return None
    direction_bins = {
        (-180, -135): "left",
        (-135, -90): "upper-left",
        (-90, -45): "upper-right",
        (-45, 0): "right",
        (0, 45): "lower-right",
        (45, 90): "bottom",
        (90, 135): "lower-left",
        (135, 180): "left",
    }
    for (low, high), label in direction_bins.items():
        if low <= theta < high:
            return label
    return "right"


def _opposite_direction(direction: str | None) -> str:
    opposites = {
        "left": "right",
        "right": "left",
        "upper-left": "lower-right",
        "upper-right": "lower-left",
        "lower-left": "upper-right",
        "lower-right": "upper-left",
        "top": "bottom",
        "bottom": "top",
    }
    return opposites.get(direction or "", "bottom")


def _build_prompt(theta: float | None) -> tuple[str, str | None, str | None]:
    if theta is None:
        prompt = (
            f"Procedural studio composite on {DEFAULT_BACKGROUND_STYLE}; preserve original product pixels; "
            "add neutral ambient contact shadow without estimated light-direction conditioning."
        )
        return prompt, None, None

    light_direction = _angle_to_direction(theta)
    shadow_direction = _opposite_direction(light_direction)
    prompt = (
        f"Procedural studio composite on {DEFAULT_BACKGROUND_STYLE}; preserve original product pixels; "
        f"use estimated light from {light_direction}; synthesize cast shadow toward {shadow_direction}."
    )
    return prompt, light_direction, shadow_direction


def _prompt_from_row(row: dict[str, str], key: str, theta: float | None) -> tuple[str, str | None, str | None]:
    prompt = row.get(f"prompt_{key}")
    light_direction = row.get(f"light_direction_{key}") or None
    shadow_direction = row.get(f"shadow_direction_{key}") or None
    if prompt:
        if key != "naive" and (not light_direction or not shadow_direction):
            _, light_direction, shadow_direction = _build_prompt(theta)
        return prompt, light_direction, shadow_direction
    return _build_prompt(theta)


def _print_wrapped(label: str, text: str, width: int = 118) -> None:
    wrapped = textwrap.fill(text, width=width, subsequent_indent=" " * (len(label) + 2))
    print(f"{label}: {wrapped}")


def display_diagnostic_rows(run_id: int, run_outdir: Path) -> list[Path]:
    """Display and save one diagnostic comparison row per product."""
    import matplotlib.image as mpimg
    import matplotlib.pyplot as plt

    raw_images_dir = Path(RAW_IMAGES_DIR)
    masks_dir = Path(MASKS_DIR)
    outputs_dir = Path(OUTPUTS_DIR)
    results_csv = outputs_dir / f"results_{run_id:03d}.csv"

    if not results_csv.exists():
        raise FileNotFoundError(f"Results CSV not found: {results_csv}. Run Cell 3.2 first.")

    with results_csv.open(newline="") as file:
        result_rows = {row["image"]: row for row in csv.DictReader(file)}

    image_paths = sorted(
        path
        for path in raw_images_dir.iterdir()
        if path.suffix.lower() in IMAGE_EXTENSIONS and path.name != TEST_IMAGE_NAME
    )
    if not image_paths:
        raise FileNotFoundError("No images found for visualization.")

    negative_prompt = (
        "No diffusion hallucination, no extra objects, no text, no product rewriting; "
        "background and shadow are generated by deterministic image compositing."
    )
    column_headers = ["Original", "SAM Product", "Naive", "Sobel-conditioned", "DPT-conditioned"]
    shown_images = image_paths[:MAX_VISUALIZATION_IMAGES]
    saved_paths = []

    for image_index, image_path in enumerate(shown_images, start=1):
        stem = image_path.stem
        row = result_rows.get(stem, {})

        theta_sobel = _parse_float(row.get("theta_sobel"))
        theta_dl = _parse_float(row.get("theta_dl"))

        prompt_naive, _, _ = _prompt_from_row(row, "naive", None)
        prompt_sobel, sobel_light, sobel_shadow = _prompt_from_row(row, "sobel", theta_sobel)
        prompt_dl, dl_light, dl_shadow = _prompt_from_row(row, "dl", theta_dl)

        print("=" * 120)
        print(f"Product {image_index}/{len(shown_images)}: {stem}")
        print(f"Angles: Sobel={_format_angle(theta_sobel)} | DPT={_format_angle(theta_dl)}")
        print("Compositing instruction:")
        print("  Naive: no estimated light angle is used; only an ambient contact shadow is added.")
        print(
            f"  Sobel: angle {_format_angle(theta_sobel)} -> light '{sobel_light or 'N/A'}' "
            f"-> shadow '{sobel_shadow or 'N/A'}' ({_format_shadow_vector(row, 'sobel')})"
        )
        print(
            f"  DPT:   angle {_format_angle(theta_dl)} -> light '{dl_light or 'N/A'}' "
            f"-> shadow '{dl_shadow or 'N/A'}' ({_format_shadow_vector(row, 'dl')})"
        )
        _print_wrapped("Instruction naive", prompt_naive)
        _print_wrapped("Instruction sobel", prompt_sobel)
        _print_wrapped("Instruction DPT", prompt_dl)
        _print_wrapped("Constraints", row.get("negative_prompt") or negative_prompt)

        comparison_paths = [
            image_path,
            masks_dir / f"{stem}_product.png",
            Path(row.get("output_naive") or Path(run_outdir) / f"{stem}_naive.png"),
            Path(row.get("output_sobel") or Path(run_outdir) / f"{stem}_sobel.png"),
            Path(row.get("output_dl") or Path(run_outdir) / f"{stem}_dl.png"),
        ]
        subtitles = [
            "input image",
            "SAM segmented product",
            f"SDCS {_format_metric(row.get('sdcs_naive'))} | LPIPS {_format_metric(row.get('lpips_naive'))}",
            f"theta {_format_angle(theta_sobel)} | shadow {_format_shadow_vector(row, 'sobel')}",
            f"theta {_format_angle(theta_dl)} | shadow {_format_shadow_vector(row, 'dl')}",
        ]

        figure, axes = plt.subplots(1, len(column_headers), figsize=(22, 4.2), squeeze=False)
        figure.suptitle(f"Run {run_id:03d}: {stem}", fontsize=14, fontweight="bold", y=1.05)

        for column_index, header in enumerate(column_headers):
            axis = axes[0][column_index]
            axis.axis("off")
            axis.set_title(header, fontsize=11, fontweight="bold", pad=8)
            comparison_path = comparison_paths[column_index]
            if comparison_path.exists():
                axis.imshow(mpimg.imread(comparison_path))
            else:
                axis.text(
                    0.5,
                    0.5,
                    "not generated",
                    ha="center",
                    va="center",
                    transform=axis.transAxes,
                    color="gray",
                    fontsize=9,
                )
            axis.set_xlabel(subtitles[column_index], fontsize=8, labelpad=6)

        plt.tight_layout()
        product_grid_path = outputs_dir / f"comparison_run_{run_id:03d}_{stem}.png"
        figure.savefig(product_grid_path, dpi=160, bbox_inches="tight")
        saved_paths.append(product_grid_path)
        plt.show()

    print("=" * 120)
    print(f"Displayed {len(shown_images)} of {len(image_paths)} image(s).")
    print("Saved product-level diagnostic rows:")
    for saved_path in saved_paths:
        print(f"  {saved_path}")
    print("Use each SAM Product image first; if segmentation is poor, generation and metrics should be interpreted cautiously.")
    return saved_paths
