import os
import sys
import importlib.util

import cv2
import numpy as np
from PIL import Image

CODE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if CODE_DIR not in sys.path:
    sys.path.insert(0, CODE_DIR)

from constants import (
    AMBIENT_SHADOW_OPACITY,
    BACKGROUND_NOISE_STRENGTH,
    DEFAULT_BACKGROUND_STYLE,
    MASKS_DIR,
    OUTPUTS_DIR,
    RAW_IMAGES_DIR,
    SHADOW_BLUR_FRACTION,
    SHADOW_OFFSET_FRACTION,
    SHADOW_OPACITY,
    TEST_GENERATED_NAME,
    TEST_IMAGE_NAME,
    TEST_MASK_NAME,
)


def angle_to_direction(theta):
    """
    Converts a geometric angle (-180 to 180) into a readable direction label.
    Angles follow image coordinates: 0=right, 90=down, -90=up.
    """
    dirs = {
        (-180, -135): "left",
        (-135, -90): "upper-left",
        (-90, -45): "upper-right",
        (-45, 0): "right",
        (0, 45): "lower-right",
        (45, 90): "bottom",
        (90, 135): "lower-left",
        (135, 180): "left",
    }
    for (lo, hi), label in dirs.items():
        if lo <= theta < hi:
            return label
    return "right"


def normalize_angle(theta):
    """Normalize an angle to the [-180, 180) degree range."""
    return ((theta + 180.0) % 360.0) - 180.0


def opposite_direction(direction):
    """Returns the opposite direction for cast-shadow placement."""
    opposites = {
        "left": "right",
        "right": "left",
        "upper-left": "lower-right",
        "upper-right": "lower-left",
        "lower-left": "upper-right",
        "lower-right": "upper-left",
        "top": "bottom",
        "bottom": "top",
    }
    return opposites.get(direction, "bottom")


def shadow_angle_from_light_angle(theta):
    """Return the cast-shadow angle implied by a foreground light angle."""
    if theta is None:
        return None
    return normalize_angle(theta + 180.0)


def shadow_vector_from_light_angle(theta, image_shape):
    """
    Return the pixel translation used for the deterministic cast shadow.

    Angles follow image coordinates: 0=right, 90=down, -90=up.
    """
    if theta is None:
        return 0, 0, None

    h, w = image_shape[:2]
    shadow_theta = np.radians(theta + 180.0)
    offset = max(6, int(max(h, w) * SHADOW_OFFSET_FRACTION))
    dx = int(np.cos(shadow_theta) * offset)
    dy = int(np.sin(shadow_theta) * offset)
    return dx, dy, shadow_angle_from_light_angle(theta)


def build_generation_prompt(theta=None, bg_style=DEFAULT_BACKGROUND_STYLE):
    """
    Builds the human-readable conditioning description used by the deterministic
    compositor. The name is kept for CSV/notebook compatibility with earlier runs.
    """
    if theta is None:
        light_dir = None
        shadow_dir = "soft contact shadow below product"
        instruction = (
            f"Procedural studio composite on {bg_style}; preserve original product pixels; "
            "add neutral ambient contact shadow without estimated light-direction conditioning."
        )
    else:
        light_dir = angle_to_direction(theta)
        shadow_dir = opposite_direction(light_dir)
        shadow_angle = shadow_angle_from_light_angle(theta)
        instruction = (
            f"Procedural studio composite on {bg_style}; preserve original product pixels; "
            f"use estimated light from {light_dir}; synthesize cast shadow toward {shadow_dir} "
            f"(continuous shadow angle {shadow_angle:.1f} degrees)."
        )

    negative_instruction = (
        "No diffusion hallucination, no extra objects, no text, no product rewriting; "
        "background and shadow are generated by deterministic image compositing."
    )
    return instruction, negative_instruction, light_dir, shadow_dir


def _normalize_mask(mask):
    mask_float = mask.astype(np.float32)
    if mask_float.max() > 1.0:
        mask_float = mask_float / 255.0
    return np.clip(mask_float, 0.0, 1.0)


def _odd_kernel(size):
    size = max(3, int(size))
    return size if size % 2 == 1 else size + 1


def _hex_to_rgb(value):
    value = value.lstrip("#")
    return np.array([int(value[i:i + 2], 16) for i in (0, 2, 4)], dtype=np.float32)


def _style_palette(bg_style):
    palettes = {
        "marble surface table": ("#f4f1eb", "#c8c3ba", "#8f9296"),
        "wooden table": ("#c79255", "#7b4d2d", "#4b2b1c"),
        "white fabric background": ("#fbfbf7", "#deded6", "#b9b9b0"),
        "concrete floor": ("#d7d7d0", "#9c9d98", "#6f716d"),
        "dark slate surface": ("#777b7a", "#343a3c", "#1b2022"),
        "outdoor grass": ("#a8b779", "#516d3b", "#2c3d24"),
    }
    return palettes.get(bg_style, palettes[DEFAULT_BACKGROUND_STYLE])


def create_studio_background(height, width, bg_style=DEFAULT_BACKGROUND_STYLE, theta=None):
    """
    Creates a clean table-and-wall studio background with subtle texture.
    This replaces unstable text-only diffusion with deterministic compositing.
    """
    top_hex, bottom_hex, accent_hex = _style_palette(bg_style)
    top = _hex_to_rgb(top_hex)
    bottom = _hex_to_rgb(bottom_hex)
    accent = _hex_to_rgb(accent_hex)

    y = np.linspace(0.0, 1.0, height, dtype=np.float32)[:, None]
    vertical = top * (1.0 - y) + bottom * y
    background = np.repeat(vertical[:, None, :], width, axis=1)

    horizon = int(height * 0.58)
    surface_y = np.linspace(0.0, 1.0, max(1, height - horizon), dtype=np.float32)[:, None]
    surface = bottom * (1.0 - surface_y) + accent * surface_y
    background[horizon:, :, :] = np.repeat(surface[:, None, :], width, axis=1)

    if theta is not None:
        light_rad = np.radians(theta)
        xx = np.linspace(-1.0, 1.0, width, dtype=np.float32)[None, :]
        yy = np.linspace(-1.0, 1.0, height, dtype=np.float32)[:, None]
        light_x = -np.cos(light_rad)
        light_y = -np.sin(light_rad)
        illumination = 0.88 + 0.18 * ((xx * light_x + yy * light_y + 1.0) / 2.0)
        background *= illumination[:, :, None]

    rng = np.random.default_rng(7)
    noise = rng.normal(0.0, BACKGROUND_NOISE_STRENGTH, size=(height, width, 1)).astype(np.float32)
    background += noise

    if "marble" in bg_style or "slate" in bg_style or "concrete" in bg_style:
        for offset in range(-width, width, max(18, width // 18)):
            color = accent * 0.55 + top * 0.45
            cv2.line(background, (offset, height), (offset + width // 2, horizon), color.tolist(), 1, cv2.LINE_AA)
    elif "wood" in bg_style:
        for x in range(0, width, max(16, width // 24)):
            cv2.line(background, (x, horizon), (x + width // 8, height), accent.tolist(), 1, cv2.LINE_AA)
    elif "fabric" in bg_style:
        for x in range(0, width, max(14, width // 28)):
            cv2.line(background, (x, 0), (x + width // 16, height), accent.tolist(), 1, cv2.LINE_AA)

    return np.clip(background, 0, 255).astype(np.uint8)


def _ambient_contact_shadow(mask_float):
    h, w = mask_float.shape
    y_indices, x_indices = np.where(mask_float > 0.5)
    shadow = np.zeros((h, w), dtype=np.float32)
    if len(y_indices) == 0:
        return shadow

    x_min, x_max = x_indices.min(), x_indices.max()
    y_max = y_indices.max()
    obj_w = max(8, x_max - x_min + 1)
    center_x = int((x_min + x_max) / 2)
    center_y = min(h - 1, y_max + max(2, int(0.025 * h)))
    axes = (max(5, int(obj_w * 0.46)), max(3, int(h * 0.025)))
    cv2.ellipse(shadow, (center_x, center_y), axes, 0, 0, 360, 1.0, -1, cv2.LINE_AA)
    kernel = _odd_kernel(min(h, w) * 0.04)
    return cv2.GaussianBlur(shadow, (kernel, kernel), 0) * AMBIENT_SHADOW_OPACITY


def synthesize_shadow(mask, theta=None):
    """
    Synthesizes a shadow from the product mask. For conditioned variants, the
    shadow is translated opposite the estimated light angle; for the naive
    variant, only a soft ambient contact shadow is used.
    """
    mask_float = _normalize_mask(mask)
    h, w = mask_float.shape
    shadow = _ambient_contact_shadow(mask_float)

    if theta is None:
        return np.clip(shadow, 0.0, 1.0)

    dx, dy, _ = shadow_vector_from_light_angle(theta, mask_float.shape)

    kernel = np.ones((5, 5), dtype=np.uint8)
    expanded = cv2.dilate((mask_float * 255).astype(np.uint8), kernel, iterations=2).astype(np.float32) / 255.0
    transform = np.float32([[1, 0, dx], [0, 1, dy]])
    cast = cv2.warpAffine(expanded, transform, (w, h), flags=cv2.INTER_LINEAR, borderValue=0)

    blur = _odd_kernel(max(h, w) * SHADOW_BLUR_FRACTION)
    cast = cv2.GaussianBlur(cast, (blur, blur), 0)
    cast *= SHADOW_OPACITY
    cast *= (1.0 - mask_float * 0.85)

    return np.clip(np.maximum(shadow, cast), 0.0, 1.0)


def composite_product(image_rgb, product_mask, theta=None, bg_style=DEFAULT_BACKGROUND_STYLE):
    """
    Creates the final composite: procedural studio background, synthetic shadow,
    and exact original product pixels pasted back through the SAM mask.
    """
    h, w, _ = image_rgb.shape
    background = create_studio_background(h, w, bg_style=bg_style, theta=theta)
    shadow_alpha = synthesize_shadow(product_mask, theta=theta)

    composite = background.astype(np.float32)
    composite *= (1.0 - shadow_alpha[:, :, None])

    mask_bool = product_mask.astype(bool)
    composite[mask_bool] = image_rgb[mask_bool]
    return Image.fromarray(np.clip(composite, 0, 255).astype(np.uint8))


def generate_background(image_rgb, product_mask, theta=None, bg_style=DEFAULT_BACKGROUND_STYLE):
    """
    Module 3: illumination-aware deterministic product compositing.
    Kept under the historical function name so app.py and main_pipeline.py do
    not need to know whether the background came from diffusion or CV geometry.
    """
    instruction, _, _, _ = build_generation_prompt(theta=theta, bg_style=bg_style)
    if os.environ.get("CV2_SHOW_GENERATION_PROMPTS", "1") == "1":
        print(f"Compositing instruction:\n  '{instruction}'", flush=True)
    return composite_product(image_rgb, product_mask, theta=theta, bg_style=bg_style)


# --- TEST BLOCK FOR COLAB ---
if __name__ == "__main__":
    test_image_path = str(RAW_IMAGES_DIR / TEST_IMAGE_NAME)
    test_mask_path = str(MASKS_DIR / TEST_MASK_NAME)
    output_path = str(OUTPUTS_DIR / TEST_GENERATED_NAME)

    if not os.path.exists(test_image_path) or not os.path.exists(test_mask_path):
        print("ACTION REQUIRED: Make sure you have run '1_segmentation.py' first!")
    else:
        image_rgb = cv2.cvtColor(cv2.imread(test_image_path), cv2.COLOR_BGR2RGB)
        mask_img = cv2.imread(test_mask_path, cv2.IMREAD_GRAYSCALE)
        mask = mask_img > 127

        illumination_path = os.path.join(os.path.dirname(__file__), "2_illumination.py")
        spec = importlib.util.spec_from_file_location("illumination", illumination_path)
        illumination = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(illumination)
        theta_sobel = illumination.estimate_light_direction_sobel(image_rgb, mask)

        print("-" * 40)
        print("Running deterministic compositor test...")
        print(f"Estimated Sobel angle: {theta_sobel:.1f} degrees")

        final_image = generate_background(image_rgb, mask, theta=theta_sobel, bg_style="wooden table")

        os.makedirs(OUTPUTS_DIR, exist_ok=True)
        final_image.save(output_path)
        print(f"OK: Success. Check {output_path} to see the composited studio photo.")
        print("-" * 40)
